AllCops:
  TargetRubyVersion: 3.4
  NewCops: disable
  Exclude:
    - "vendor/**/*"
    - "ffi-wrapper/target/**/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
